### ISSUE TITLE
Training INN

### ISSUE THREAD

**Issue by DreamyRainforest** [Zhangyanbo/INNLab#16]
How do I train INN with my dataset?

**Comment by Zhangyanbo** [comment]
You can read this paper as reference: 
* Dinh, Laurent, Jascha Sohl-Dickstein, and Samy Bengio. “Density Estimation Using Real NVP.” ArXiv:1605.08803 [Cs, Stat], February 27, 2017. http://arxiv.org/abs/1605.08803.
